-- (c) 2009-2016 TNO, The Hague, the Netherlands. All copyrights and other intellectual property rights reserved.
-- This file is included in the Eclipse input deck for the "Brugge" field, with main file BRUGGE60K_FY-SF-KM-1-1.DATA.

-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : peterse
-- Date        : Tuesday, December 06 2016 10:18:49
-- Project     : Brugge_60K_ResEng.pet
-- Generated ]

INIT                                   -- Generated : Petrel

GRIDFILE                               -- Generated : Petrel
  0 1 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

-- Format      : Generic ECLIPSE style (ASCII) grid geometry and properties (*.GRDECL)
-- Exported by : Petrel 2008.1 Schlumberger
-- User name   : epeters
-- Date        : Monday, April 27 2009 12:54:33
-- Project     : Brugge_60K_ResEng.pet
-- Grid        : Part of 60K Grid

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  -4700.74 6935.19 -4700.74 7935.19 -3700.74 7935.19 /

PINCH                                  -- Generated : Petrel
  /

FAULTS                                 -- Generated : Petrel
-- FAULTS keyword exported here to support THPRESFT keyword data. 
-- Matrix Faults

-- NAME          IX1  IX2     IY1  IY2     IZ1  IZ2    FACE

-- NBF is boundary fault and therefore it IS NOT defined in the FAULTS keyword 
 
-- NAME          IX1  IX2     IY1  IY2     IZ1  IZ2    FACE
'INTERNAL' 64 64 13 13 1 9 'Y+' / 
'INTERNAL' 65 65 13 13 1 9 'Y+' / 
'INTERNAL' 66 66 13 13 1 9 'Y+' / 
'INTERNAL' 67 67 13 13 1 9 'Y+' / 
'INTERNAL' 68 68 13 13 1 9 'Y+' / 
'INTERNAL' 69 69 13 13 1 9 'Y+' / 
'INTERNAL' 70 70 13 13 1 9 'Y+' / 
'INTERNAL' 71 71 13 13 1 9 'Y+' / 
'INTERNAL' 72 72 13 13 1 9 'Y+' / 
'INTERNAL' 73 73 13 13 1 9 'Y+' / 
'INTERNAL' 74 74 13 13 1 9 'Y+' / 
'INTERNAL' 75 75 13 13 1 9 'Y+' / 
'INTERNAL' 76 76 13 13 1 9 'Y+' / 
'INTERNAL' 77 77 13 13 1 9 'Y+' / 
'INTERNAL' 78 78 13 13 1 9 'Y+' / 
'INTERNAL' 79 79 13 13 1 9 'Y+' / 
'INTERNAL' 80 80 13 13 1 9 'Y+' / 
'INTERNAL' 81 81 13 13 1 9 'Y+' / 
'INTERNAL' 82 82 13 13 1 9 'Y+' / 
'INTERNAL' 83 83 13 13 1 9 'Y+' / 
'INTERNAL' 84 84 13 13 1 9 'Y+' / 
'INTERNAL' 85 85 13 13 1 9 'Y+' / 
'INTERNAL' 85 85 13 13 1 9 'X+' / 
'INTERNAL' 86 86 12 12 1 9 'Y+' / 
'INTERNAL' 86 86 12 12 1 9 'X+' / 
'INTERNAL' 87 87 11 11 1 9 'Y+' / 
'INTERNAL' 87 87 11 11 1 9 'X+' / 
'INTERNAL' 88 88 10 10 1 9 'Y+' / 
'INTERNAL' 88 88 10 10 1 9 'X+' / 
'INTERNAL' 89 89 9 9 1 9 'Y+' / 
'INTERNAL' 89 89 9 9 1 9 'X+' / 
'INTERNAL' 90 90 8 8 1 9 'Y+' / 
'INTERNAL' 90 90 8 8 1 9 'X+' / 
'INTERNAL' 91 91 7 7 1 9 'Y+' / 
'INTERNAL' 91 91 7 7 1 9 'X+' / 
'INTERNAL' 92 92 6 6 1 9 'Y+' / 
'INTERNAL' 92 92 6 6 1 9 'X+' / 
'INTERNAL' 92 92 5 5 1 9 'X+' / 
'INTERNAL' 93 93 4 4 1 9 'Y+' / 
'INTERNAL' 93 93 4 4 1 9 'X+' / 
'INTERNAL' 94 94 3 3 1 9 'Y+' / 
'INTERNAL' 94 94 3 3 1 9 'X+' / 
'INTERNAL' 94 94 2 2 1 9 'X+' / 
'INTERNAL' 95 95 1 1 1 9 'Y+' / 
'INTERNAL' 95 95 1 1 1 9 'X+' / 

-- Mapping of unique fault names to full fault names (matrix):
-- NBF ==> NBF
-- INTERNAL ==> Internal Fault 1
 
/


