-- (c) 2009-2016 TNO, The Hague, the Netherlands. All copyrights and other intellectual property rights reserved.
-- This file is included in the Eclipse input deck for the "Brugge" field, with main file BRUGGE60K_FY-SF-KM-1-1.DATA.

-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : peterse
-- Date        : Tuesday, December 06 2016 10:18:50
-- Project     : Brugge_60K_ResEng.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          1700          170         1678            0 1* 1* 0 0 0 /

RPTRST                                 -- Generated : Petrel
  BASIC=3 /

RPTSOL                                 -- Generated : Petrel
  RESTART=2 FIP /

