-- (c) 2009-2016 TNO, The Hague, the Netherlands. All copyrights and other intellectual property rights reserved.
-- This file is included in the Eclipse input deck for the "Brugge" field, with main file BRUGGE60K_FY-SF-KM-1-1.DATA.

-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : peterse
-- Date        : Tuesday, December 06 2016 10:18:50
-- Project     : Brugge_60K_ResEng.pet
-- Generated ]

WWGR                                   -- Generated : Petrel
  /

FWGR                                   -- Generated : Petrel

WWCT                                   -- Generated : Petrel
  /

FWCT                                   -- Generated : Petrel

WTHP                                   -- Generated : Petrel
  /

WVPR                                   -- Generated : Petrel
  /

FVPR                                   -- Generated : Petrel

WVIR                                   -- Generated : Petrel
  /

FVIR                                   -- Generated : Petrel

WWPR                                   -- Generated : Petrel
  /

FWPR                                   -- Generated : Petrel

WOPR                                   -- Generated : Petrel
  /

FOPR                                   -- Generated : Petrel

FPPW                                   -- Generated : Petrel

FPPO                                   -- Generated : Petrel

WBP9                                   -- Generated : Petrel
  /

WBP5                                   -- Generated : Petrel
  /

WBP4                                   -- Generated : Petrel
  /

WBP                                    -- Generated : Petrel
  /

FPR                                    -- Generated : Petrel

WWIR                                   -- Generated : Petrel
  /

FWIR                                   -- Generated : Petrel

WOIR                                   -- Generated : Petrel
  /

FOIR                                   -- Generated : Petrel

WGOR                                   -- Generated : Petrel
  /

FGOR                                   -- Generated : Petrel

WBHP                                   -- Generated : Petrel
  /

WMVFP
  /

WSTAT
  /

