/* Cube Clubhouse - Copyright (c) 2026 Ira Learning LLC. All rights reserved. Proprietary software. See LICENSE, or the Licence page inside the app. */
/*
 * build-pages.js - the two web pages App Store Connect asks for a link to: a privacy
 * policy and a support page. Put both files on any web host and paste their addresses
 * into App Store Connect (App Privacy > Privacy Policy URL, and the version's Support URL).
 *
 * The privacy policy is the app's own Privacy section, as the iPhone and iPad app shows
 * it, so the policy people read on the web can never say something different from the
 * app. Run this after changing that section; the unit tests fail until you do.
 *
 *     node ios/app-store/build-pages.js
 *
 * Both pages are self-contained: no fonts, scripts, images or trackers are loaded.
 */
const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const ROOT = path.join(HERE, '..', '..');

function build() {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const article = /<article id="privacy" class="info-card">([\s\S]*?)<\/article>/.exec(html);
  if (!article) throw new Error('index.html has no Privacy section');
  const version = /MARKETING_VERSION = ([\d.]+);/.exec(
    fs.readFileSync(path.join(HERE, '..', 'CubeClubhouse.xcodeproj', 'project.pbxproj'), 'utf8'))[1];

  let body = article[1]
    .replace(/<span class="w-web">[\s\S]*?<\/span>/g, '')           // the browser's wording
    .replace(/<span class="w-ios">([\s\S]*?)<\/span>/g, '$1')        // the app's wording
    .replace(/this\s+<span class="device-name">device<\/span>/g, 'your device')
    .replace(/<span class="device-name">device<\/span>/g, 'device')
    .replace('<b>Clear Saved Progress</b> above', '<b>Clear Saved Progress</b> on the app\'s About page')
    .replace(/<h2>Privacy<\/h2>/, '');
  for (const left of ['device-name', 'w-ios', 'w-web', '<button', ' above,']) {
    if (body.includes(left)) throw new Error('the privacy policy still contains "' + left + '"');
  }

  const privacy = page('Cube Clubhouse Privacy Policy', `
    <h1>Cube Clubhouse<sup>®</sup> Privacy Policy</h1>
    <p class="note">For Cube Clubhouse on iPhone and iPad, version ${version}. This is the same text the app
      shows on its Privacy page.</p>
    ${body.trim()}
    <p class="note"><a href="support.html">Support</a></p>`);

  const support = page('Cube Clubhouse Support', `
    <h1>Cube Clubhouse<sup>®</sup> Support</h1>
    <p class="strong">Cube Clubhouse helps anyone, of any age, learn to solve a Cube step by step. It is
      free, needs no account and works without an internet connection.</p>

    <h2>Contact us</h2>
    <p>Email Ira Learning LLC at <b>iralearningllc@gmail.com</b>. We read every message. Please tell us
      which device you use (iPhone or iPad) and what you were doing when the problem happened.</p>
    <p class="note">A note for children: please ask your parent or guardian to send the email for you,
      from their own email address.</p>

    <h2>Common questions</h2>
    <h3>Where are my stars and times kept?</h3>
    <p>Only on your device, inside the app, and in your own iCloud or computer backup if you make one.
      There is no account, so they do not move between devices on their own.</p>
    <h3>How do I start again?</h3>
    <p>Open <b>About</b> at the bottom of the app and tap <b>Clear Saved Progress</b>. The app asks
      before it erases anything.</p>
    <h3>The steps do not match my cube.</h3>
    <p>It is almost always the way the cube is held. The middle squares never move, so check that the
      centres on top and in front are the colours the step names. In <b>My Real Cube</b>, the steps are
      only as right as the colours painted in, so check each side.</p>
    <h3>The spinning cube makes me uncomfortable.</h3>
    <p>Turn on Reduce Motion in Settings › Accessibility › Motion; the cube then changes without
      spinning. Stop and take a break if you feel unwell.</p>
    <h3>Does it need the internet?</h3>
    <p>No. It makes no network requests at all, and every part works in Aeroplane Mode.</p>

    <p class="note"><a href="privacy-policy.html">Privacy Policy</a> · © 2026 Ira Learning LLC. All rights
      reserved. Cube Clubhouse® is a registered trademark of Ira Learning LLC.</p>`);

  return { 'privacy-policy.html': privacy, 'support.html': support };
}

function page(title, content) {
  return `<!doctype html>
<!-- Generated by ios/app-store/build-pages.js from index.html. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
<meta name="referrer" content="no-referrer">
<title>${title}</title>
<style>
  :root { color-scheme: light dark; --bg: #f6f3ec; --ink: #2b3040; --muted: #5d6272; --accent: #3a5a86; --card: #fffdf8; }
  @media (prefers-color-scheme: dark) { :root { --bg: #1d2029; --ink: #ebe7dc; --muted: #b4b0a6; --accent: #9fb9dd; --card: #262a35; } }
  body { margin: 0; background: var(--bg); color: var(--ink);
    font: 17px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  main { max-width: 720px; margin: 0 auto; padding: 24px 16px 48px; }
  article { background: var(--card); border-radius: 16px; padding: 8px 22px 18px; }
  h1 { font-size: 1.6rem; line-height: 1.25; margin: 18px 0 6px; }
  h2 { font-size: 1.2rem; margin: 22px 0 4px; }
  h3 { font-size: 1.05rem; margin: 18px 0 4px; color: var(--accent); }
  ul { padding-left: 22px; } li { margin: 4px 0; }
  .note, .info-note { color: var(--muted); font-size: 0.92rem; }
  .strong, .info-strong { font-weight: 600; }
  a { color: var(--accent); }
  sup { font-size: 0.55em; }
</style>
</head>
<body><main><article>
${content}
</article></main></body>
</html>
`;
}

module.exports = { build };

if (require.main === module) {
  for (const [name, text] of Object.entries(build())) {
    fs.writeFileSync(path.join(HERE, name), text);
    console.log('wrote ios/app-store/' + name);
  }
}
