"""Generate the corner-point grid include file for CORNERPOINT_DOME.DATA.

A 20 x 20 x 5 dome (anticline) with slightly tilted pillars; writes COORD,
ZCORN, PORO and PERMX/PERMY/PERMZ in FIELD units to include/DOME_GRID.INC.
"""
import os

import numpy as np

NX, NY, NZ = 20, 20, 5
LX, LY = 6000.0, 6000.0
TOP, RELIEF = 7000.0, 250.0
DZ = np.array([30.0, 25.0, 40.0, 35.0, 30.0])


def top_depth(x, y):
    r2 = ((x - LX / 2) / (LX / 2)) ** 2 + ((y - LY / 2) / (LY / 2)) ** 2
    return TOP + RELIEF * r2


def main(path):
    xs = np.linspace(0, LX, NX + 1)
    ys = np.linspace(0, LY, NY + 1)
    total = DZ.sum()
    coord = []
    for j in range(NY + 1):
        for i in range(NX + 1):
            x, y = xs[i], ys[j]
            zt = top_depth(x, y) - 10
            zb = zt + total + 400
            tilt = 0.02 * (x - LX / 2)          # pillars lean slightly outwards
            coord += [x, y, zt, x + tilt, y, zb]
    zc = np.zeros((2 * NZ, 2 * NY, 2 * NX))
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                for dj in (0, 1):
                    for di in (0, 1):
                        x, y = xs[i + di], ys[j + dj]
                        t = top_depth(x, y) + DZ[:k].sum()
                        zc[2 * k, 2 * j + dj, 2 * i + di] = t
                        zc[2 * k + 1, 2 * j + dj, 2 * i + di] = t + DZ[k]
    rng = np.random.default_rng(7)
    n = NX * NY * NZ
    layer_k = np.repeat([300.0, 80.0, 500.0, 150.0, 40.0], NX * NY)
    permx = layer_k * np.exp(rng.normal(0, 0.4, n))
    poro = np.clip(0.12 + 0.03 * np.log10(permx / 10.0) + rng.normal(0, 0.01, n), 0.05, 0.32)

    def block(name, vals, fmt):
        lines = [name]
        for s in range(0, len(vals), 6):
            lines.append("  " + " ".join(fmt.format(v) for v in vals[s:s + 6]))
        lines.append("/\n")
        return "\n".join(lines)

    with open(path, "w") as fh:
        fh.write("-- Corner-point dome grid generated by tools/make_dome_grid.py\n")
        fh.write(block("COORD", coord, "{:.2f}"))
        fh.write(block("ZCORN", zc.ravel(), "{:.2f}"))
        fh.write(block("PORO", poro, "{:.4f}"))
        fh.write(block("PERMX", permx, "{:.2f}"))
        fh.write(block("PERMY", permx, "{:.2f}"))
        fh.write(block("PERMZ", 0.1 * permx, "{:.3f}"))


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    main(os.path.join(here, "..", "include", "DOME_GRID.INC"))
